import base from '@carbonplan/theme'

export default {
  ...base,
  tags: {
    dac: 'purple',
    forests: 'green',
    mineralization: 'grey',
    biomass: 'yellow',
    burial: 'yellow',
    ocean: 'teal',
    alkalinity: 'teal',
    soil: 'orange',
    reforestation: 'green',
    'redd+': 'green',
    biochar: 'yellow',
    storage: 'yellow',
    injection: 'grey',
    phytoplankton: 'green',
    ifm: 'green',
    agroforestry: 'green',
    concrete: 'grey',
    aggregate: 'grey',
    olivine: 'grey',
    basalt: 'grey',
    asphalt: 'grey',
    wood: 'yellow',
    farming: 'orange',
    grazing: 'orange',
    conversion: 'orange',
    macroalgae: 'green',
    wetlands: 'green',
    insulation: 'yellow',
    restoration: 'orange',
  },
}
