import base from '@carbonplan/theme'

export default {
  ...base,
  text: {
    default: {
      color: 'text',
      fontFamily: 'body',
      letterSpacing: 'body',
    },
    link: {
      color: 'text',
      '&:active': {
        color: 'text',
      },
      '&:hover': {
        color: 'secondary',
      },
      textDecoration: 'underline',
      cursor: 'pointer',
    },
    description: {
      fontSize: [2],
      fontFamily: 'body',
      letterSpacing: 'body',
      marginBlockStart: '0.3em',
      mb: [1],
    },
    metric: {
      value: {
        fontFamily: 'monospace',
        fontSize: [3],
        textAlign: 'right',
        mt: ['5px'],
      },
      label: {
        fontFamily: 'monospace',
        fontSize: [2],
        mt: ['6px'],
        textTransform: 'capitalize',
      },
      comment: {
        fontFamily: 'faux',
        fontSize: [1],
        color: 'secondary',
        letterSpacing: 'faux',
        lineHeight: 'small',
        mt: [0],
        mb: [2],
      },
      units: {
        fontFamily: 'monospace',
        color: 'secondary',
        fontSize: [1],
        ml: [2],
        textTransform: 'normal',
      },
      rating: {
        display: 'inline-block',
        ml: [3],
        fontSize: ['18px'],
      },
    },
    arrow: {
      ml: [2],
      color: 'text',
      fontSize: [4],
      position: 'relative',
      top: '4px',
      display: 'inline-block',
      textDecoration: 'none',
      lineHeight: 0,
      '&:active': {
        color: 'text',
      },
      '&:hover': {
        color: 'secondary',
        borderColor: 'secondary',
      },
    },
  },
  forms: {
    input: {
      fontSize: [2],
      pt: ['4px'],
      pb: ['6px'],
      pl: [0],
      pr: [0],
      fontFamily: 'monospace',
      borderRadius: '0px',
      borderStyle: 'solid',
      borderColor: 'muted',
      borderWidth: '0px',
      borderBottomWidth: '0px',
      textAlign: 'right',
    },
    select: {
      cursor: 'pointer',
      WebkitAppearance: 'none',
      MozAppearance: 'none',
      p: [1],
      pl: [0],
      width: '175px',
      mt: [3],
      color: 'text',
      bg: 'background',
      border: 'none',
      borderBottomStyle: 'solid',
      borderBottomWidth: '1px',
      borderBottomColor: 'text',
      borderRadius: '0px',
      fontFamily: 'heading',
      fontSize: [1],
    },
    radio: {
      cursor: 'pointer',
    },
    label: {
      cursor: 'pointer',
    },
  },
  layout: {
    container: {
      maxWidth: '1150px',
      '@media only screen and (min-width: 100em)': {
        maxWidth: '1500px',
      },
    },
  },
  sizes: {
    sidebar: 500,
    chart: 400,
    main: 250,
  },
  badges: {
    primary: {
      letterSpacing: 'wide',
      cursor: 'pointer',
      color: 'primary',
      borderStyle: 'solid',
      borderColor: 'primary',
      borderWidth: '0px',
      borderBottomWidth: '1px',
      bg: 'background',
      borderRadius: '0px',
      textTransform: 'uppercase',
      mb: [2],
      pt: ['1px'],
      pb: ['2px'],
      pl: [0],
      pr: [0],
      fontSize: [1],
      fontFamily: 'monospace',
    },
  },
  links: {
    nav: {
      color: 'primary',
      '&:active': {
        color: 'primary',
      },
      '&:hover': {
        color: 'background',
        backgroundColor: 'primary',
      },
      fontFamily: 'heading',
      borderRadius: [2],
      textDecoration: 'none',
      fontSize: [2],
      fontWeight: 'bold',
      cursor: 'pointer',
      p: [2],
      pb: [1],
    },
    arrow: {
      ml: [2],
      fontSize: [4],
      position: 'relative',
      top: '4px',
      display: 'inline-block',
      textDecoration: 'none',
      lineHeight: 0,
      cursor: 'pointer',
      color: 'text',
      '&:active': {
        color: 'text',
      },
      '&:hover': {
        color: 'secondary',
        borderColor: 'secondary',
      },
    },
  },
  tags: {
    mineralization: 'grey',
    soil: 'orange',
    biomass: 'yellow',
    forests: 'green',
    ocean: 'teal',
    dac: 'purple',
    biochar: 'yellow',
    materials: 'yellow',
    broker: 'grey',
    beccs: 'yellow',
    reforestation: 'green',
    'avoided conversion': 'green',
    agroforestry: 'green',
    burial: 'yellow',
    phytoplankton: 'teal',
    injection: 'grey',
  },
}
