import base from '@carbonplan/theme'

export default {
  ...base,
  text: {
    label: {
      fontFamily: 'mono',
      letterSpacing: 'mono',
      fontSize: [1],
      textTransform: 'uppercase',
      color: 'secondary',
      mt: ['3px'],
      userSelect: 'none',
    },
  },
  tags: {
    dac: 'purple',
    forests: 'green',
    mineralization: 'grey',
    biomass: 'yellow',
    ocean: 'teal',
    soil: 'orange',
    reforestation: 'green',
    'redd+': 'green',
    biochar: 'yellow',
    storage: 'yellow',
    injection: 'grey',
    phytoplankton: 'green',
    ifm: 'green',
    agroforestry: 'green',
    concrete: 'grey',
    aggregate: 'grey',
    olivine: 'grey',
    wood: 'yellow',
    farming: 'orange',
    grazing: 'orange',
    conversion: 'orange',
    macroalgae: 'green',
    wetlands: 'green',
    insulation: 'yellow',
    restoration: 'orange',
  },
}
